### PR TITLE
fix the alt key on the keys plugin

### PR DESCRIPTION
**Pull request by keithbeaudoin**
fix the alt key on the keys plugin

### CODE REVIEW

**Comment by kaievns** [comment]
Hey Keith,

Hmm... it broke OSX + FF. Could you please try it like that?

```
[RightJS.Document, RightJS.Element, RightJS.Window].each('include', {
  on: function() {
    var args = RightJS.$A(arguments), name = args[0];

    if (typeof(name) === 'string') {
      var key = name.split(/[\+\-\_ ]+/);
      key = (key[key.length - 1] || '').toUpperCase();

      if (key in RightJS.Event.Keys || /^[A-Z0-9]$/.test(key)) {
        var meta   = /(^|\+|\-| )(meta|alt)(\+|\-| )/i.test(name),
            ctrl   = /(^|\+|\-| )(ctl|ctrl)(\+|\-| )/i.test(name),
            shift  = /(^|\+|\-| )(shift)(\+|\-| )/i.test(name),
            code   = RightJS.Event.Keys[key] || key.charCodeAt(0),
            orig   = args.slice(1),
            method = orig.shift();

        if (typeof(method) === 'string') {
          method = this[method] || function() {};
        }

        // replacing the arguments
        args = ['keydown', function(event) {
          var raw = event._;
          if (
            (raw.keyCode === code) &&
            (!meta  || raw.metaKey || raw.altKey) &&
            (!ctrl  || raw.ctrlKey) &&
            (!shift || raw.shiftKey)
          ) {
            return method.call(this, [event].concat(orig));
          }
        }];
      }
    }

    return this.$super.apply(this, args);
  }
});
```

**Comment by keithbeaudoin** [comment]
Good everything work too in OSX + Safari Version 5.0.3 (6533.19.4) with your version.

**Comment by keithbeaudoin** [comment]
you will push the fix or you want me to push it

**Comment by kaievns** [comment]
no worries, I simply merged both versions.

thanks for the patch!

**Pull request merged**
